from snakemake.utils import min_version
import glob
min_version("5.3.0")

configfile: "config/config.yml"

PATHS = config.get("paths", {})
RESULT_PATHS = PATHS.get("results", {})

MAIN_PATH = PATHS.get("main", ".")
DATA_PATH = PATHS.get("data", "snakemake_data") # fastqs and references

RESULTS_PATH_STAR = RESULT_PATHS.get("star", ".")
RESULTS_PATH_STARsoloTE = RESULT_PATHS.get("starsolo_te", ".")
RESULTS_PATH_SoloTE = RESULT_PATHS.get("solote", ".")
RESULTS_PATH_Stellarscope = RESULT_PATHS.get("stellarscope", ".")

BASE_DIR = workflow.current_basedir


# get names of real samples
REAL_DATASET_SAMPLE_PAIRS = [
    (dataset, sample_id)
    for dataset, settings in config["datasets"].items()
    if not settings["simulated"]
    for sample_id in settings["sample_ids"]
]
REAL_DATASET_NAMES, REAL_SAMPLE_IDS = zip(*REAL_DATASET_SAMPLE_PAIRS)

# get names of simulated samples
SIMULATED_DATASET_SAMPLE_PAIRS = [
    (dataset, sample_id)
    for dataset, settings in config["datasets"].items()
    if settings["simulated"]
    for sample_id in settings["sample_ids"]
]
SIMULATED_DATASET_NAMES, SIMULATED_SAMPLE_IDS = zip(*SIMULATED_DATASET_SAMPLE_PAIRS)

rule allout:
    """
    Collect the main outputs of the workflow.
    """
    input:
        # REAL DATASETS
        ## SoloTE
        expand(
            RESULTS_PATH_SoloTE
            + "/results/SoloTEout/{dataset}/{sample_id}",
            zip,
            dataset=REAL_DATASET_NAMES,
            sample_id=REAL_SAMPLE_IDS,
        ),
        ## Stellarscope
        expand(
            RESULTS_PATH_Stellarscope
            + "/results/stellarscope_out/{dataset}/{sample_id}/pseudobulk",
            zip,
            dataset=REAL_DATASET_NAMES,
            sample_id=REAL_SAMPLE_IDS,
        ),
        RESULTS_PATH_Stellarscope + "/results/stellarscope_out/10xPBMC/pbmc8k/celltype/",
        ## STARsolo
        expand(
            RESULTS_PATH_STARsoloTE
            + "/results/STARsolo_EM_TE/{dataset}/{sample_id}/TE_Solo.out",
            zip,
            dataset=REAL_DATASET_NAMES,
            sample_id=REAL_SAMPLE_IDS,
        ),

        # SIMULATED DATASETS
        ## SoloTE
        ### default
        expand(
            RESULTS_PATH_SoloTE
            + "/results/SoloTEout/{dataset}/{sample_id}",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        ### thr 0
        expand(
            RESULTS_PATH_SoloTE
            + "/results/SoloTEout_thr0/{dataset}/{sample_id}",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        ### thr 1
        expand(
            RESULTS_PATH_SoloTE
            + "/results/SoloTEout_thr1/{dataset}/{sample_id}",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        ### thr 2
        expand(
            RESULTS_PATH_SoloTE
            + "/results/SoloTEout_thr2/{dataset}/{sample_id}",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        ## Stellarscope
        ### pseudobulk
        expand(
            RESULTS_PATH_Stellarscope
            + "/results/stellarscope_out/{dataset}/{sample_id}/pseudobulk",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        ### thr 0.9
        expand(
            RESULTS_PATH_Stellarscope
            + "/results/stellarscope_out/simulated_mm_RA/{sample_id}/pseudobulk_thr0.9",
            sample_id=[
                "old",
                "young"
            ],
        ),
        ### 
        expand(
            RESULTS_PATH_Stellarscope
            + "/results/stellarscope_out/{dataset}_pseudobulk_onestep/{sample_id}",
            zip,
            dataset=SIMULATED_DATASET_NAMES,
            sample_id=SIMULATED_SAMPLE_IDS,
        ),
        # Standard STARsolo TE
        [
            RESULTS_PATH_STARsoloTE
            + f"/results/STARsolo_EM_TE/{dataset}/{sample_id}/TE_Solo.out"
            for dataset, sample_id in SIMULATED_DATASET_SAMPLE_PAIRS
            if dataset != "simulated_mm_RA_wGenes"
        ],
        # STARsolo TEs + GENES
        RESULTS_PATH_STARsoloTE
        + "/results/STARsolo_EM_TEwGenes/"
          "simulated_mm_RA_wGenes/all/TE_Solo.out"

# rule generate_rulegraph:
#     """
#     Generate a rulegraph for the workflow.
#     """
#     output:
#         "workflow/schemas/rulegraph.png"
#     params:
#         basedir=BASE_DIR
#     shell:
#         """
#         snakemake --snakefile workflow/Snakefile --rulegraph | dot -Tpng > {output}
#         echo {params.basedir}
#         """

# rule generate_dag:
#     """
#     Generate a dag for the workflow.
#     """
#     output:
#         "workflow/schemas/dag.png"
#     shell:
#         """
#         snakemake --snakefile workflow/Snakefile --dag | dot -Tpng > {output}
#         """

include: "rules/common.smk"
include: "rules/star_align.smk"
include: "rules/starSolo_TE.smk"
include: "rules/soloTE.smk"
include: "rules/stellarscope.smk"