paths:
  main: "." # full path of the repo
  data: "snakemake_data" # folder where input data is stored
  results: # folders to save results
    star: "."
    starsolo_te: "."
    solote: "."
    stellarscope: "."

datasets:
  10xPBMC:
    sample_ids:
      - pbmc8k
    genome: "hg38"
    read_length: 98
    UMI_length: "10"
    whitelist: "data/whitelists/10xPBMC_sub_whitelist.tsv.gz"
    strandedness: "Forward"
    simulated: false
  10xMouse_PBMC:
    sample_ids:
      - 10k
    genome: "mm10"
    chromium: "v3"
    read_length: 90
    UMI_length: "12  --soloCBlen 16 --soloBarcodeReadLength 0"
    whitelist: "data/whitelists/3M-february-2018.txt.gz"
    strandedness: "Forward"
    simulated: false
    download:
      wget:
        - https://s3-us-west-2.amazonaws.com/10x.files/samples/cell-exp/6.0.0/SC3_v3_NextGem_DI_CellPlex_Mouse_PBMC_10K_Multiplex/SC3_v3_NextGem_DI_CellPlex_Mouse_PBMC_10K_Multiplex_fastqs.tar
    #https://www.10xgenomics.com/datasets/10-k-mouse-pbm-cs-multiplexed-2-cm-os-3-1-standard-6-0-0
  10xHuman_8CLC:
    sample_ids:
      - DUX4
    genome: "hg38"
    read_length: 90
    UMI_length: "12  --soloCBlen 16 --soloBarcodeReadLength 0"
    whitelist: "data/whitelists/3M-february-2018.txt.gz"
    strandedness: "Forward"
    simulated: false
    download:
      SRA:
        - SRR16975081
    # https://pmc.ncbi.nlm.nih.gov/articles/PMC8901440/#sec4
  10xMouse_RA:
    sample_ids: 
      - LIF
    genome: "mm10"
    read_length: 101 
    UMI_length: "12  --soloCBlen 16 --soloBarcodeReadLength 0"
    whitelist: "data/whitelists/3M-february-2018.txt.gz"
    strandedness: "Forward"
    simulated: false
  10xHorgue:
    sample_ids:
      - SRR16188429
      - SRR16188430
      - SRR16188431
      - SRR16188432
      - SRR16188433
      - SRR16188434
      - SRR16188435
    genome: "mm10"
    read_length: 101
    UMI_length: "12  --soloCBlen 16 --soloBarcodeReadLength 0"
    whitelist: "whitelists/737K-august-2016.txt.gz"
    simulated: false
  simulated_mm_RA_50kRpC:
      sample_ids:
        - old
        - young
        - all
      genome: "mm10"
      read_length: 101
      UMI_length: "10"
      whitelist: "data/whitelists/737K-august-2016.txt.gz"
      strandedness: "Unstranded"
      simulated: true
  simulated_mm_RA_20kRpC:
    sample_ids:
      - old
      - young
      - all
    genome: "mm10"
    read_length: 101
    UMI_length: "10"
    whitelist: "data/whitelists/737K-august-2016.txt.gz"
    strandedness: "Unstranded"
    simulated: true
  simulated_mm_RA_5kRpC:
    sample_ids:
      - old
      - young
      - all
    genome: "mm10"
    read_length: 101
    UMI_length: "10"
    whitelist: "data/whitelists/737K-august-2016.txt.gz"
    strandedness: "Unstranded"
    simulated: true
  simulated_mm_RA:
    sample_ids:
      - old
      - young
      - all
    genome: "mm10"
    read_length: 101
    UMI_length: "10"
    whitelist: "data/whitelists/737K-august-2016.txt.gz"
    strandedness: "Unstranded"
    simulated: true
  simulated_mm_RA_wGenes:
    sample_ids:
      - all
    genome: "mm10"
    read_length: 101
    UMI_length: "10"
    whitelist: "data/whitelists/737K-august-2016.txt.gz"
    strandedness: "Unstranded"
    platform: "10X"
    simulated: True


genomes:
  mm10:
    fasta: "references/mm10/GRCm38.p4.genome.fa.gz"
    gtf: "references/mm10/gencode.vM10.annotation.gtf.gz"
    rmsk_gtf: "TEannotation/mm10_GENCODE_rmsk_TE.gtf.gz"
    GeneTE_gtf: ""
    cr_id: "GRCm39"
    cr_version: "M26"
  hg38:
    fasta: "references/hg38/GRCh38.p14.genome.fa.gz"
    gtf: "references/hg38/gencode.v30.annotation.gtf.gz"
    rmsk_gtf: "TEannotation/hg38_GENCODE_rmsk_TE.gtf.gz"
    GeneTE_gtf: ""
    cr_id: "GRCh38"
    cr_version: "35"

conf:
  best:
    extra_params: "--outSAMmultNmax 1"
  score:
    extra_params: ""